[project]
authors = ["saida <eneisyou@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Biological_Information_Processing"
platforms = ["osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.13"
chardet = ">=5.2.0,<6"
numpy = ">=2.1.3,<3"
matplotlib = ">=3.9.3,<4"
scipy = ">=1.14.1,<2"
